{%- for env in values.environments %}
# values-{{ env }}.yaml
environment: {{ env }}
accountId: "ACCOUNT_ID_{{ env | upper }}"
region: us-east-1

replicas: {% if env == 'dev' %}1{% elif env == 'hml' %}2{% else %}3{% endif %}

resources:
  limits:
    cpu: {% if env == 'prd' %}"1000m"{% else %}"500m"{% endif %}
    memory: {% if env == 'prd' %}"1Gi"{% else %}"512Mi"{% endif %}
  requests:
    cpu: {% if env == 'prd' %}"500m"{% else %}"250m"{% endif %}
    memory: {% if env == 'prd' %}"512Mi"{% else %}"256Mi"{% endif %}

ingress:
  enabled: {% if env == 'prd' %}true{% else %}false{% endif %}
  host: {% if env == 'prd' %}${{ values.sigla | lower }}-${{ values.appName }}.devopstia.com{% else %}""{% endif %}
---
{%- endfor %}
